config:
  install:
    k8s_tools: true
    shell_tools: true
    network_tools: true
    kafka_tools: true
    coding_tools: true
    db_tools: true
    redis_tools: true
    macos_tools: true
    tools: true
    dotfiles: true
