config:
  install:
    container: true
    k8s: true
    shell: true
    network: true
    kafka: true
    coding: true
    db: true
    redis: true
    macos: true
    tools: true
  restore:
    gpg: true
    age: true
    dotfiles: true
