---
# install all common tools here
- name: Install common tools
  homebrew:
    name: 
      - tmux
      - jq
      - yq
      - yamllint
      - sops
      - age
      - gnupg
      - k6
      - pass-otp
      - md5sha1sum
      - sevenzip
      - htop
      - ntopng
      - stow
      - neovim
      - go-task
    state: present

- name: Install common gui tools
  homebrew_cask:
    name: 
      - iterm2
    state: present